### ISSUE TITLE
Erro skill.c (ao logar && quando mobs attack).

### ISSUE THREAD

**Issue by Hyroshima** [brAthena/brAthena#1]
O problema ocorre quando se cria um novo char (noviço) e após fazer login ocorre o erro, e também quando um mob attack alguém.

![xvnw128 1](https://cloud.githubusercontent.com/assets/12840357/8100336/bf98dc44-0fe0-11e5-9a53-1528527a29d9.png)

![rwlr0ny 1](https://cloud.githubusercontent.com/assets/12840357/8100339/c7c3f106-0fe0-11e5-9c57-085d743c37f0.png)

**Comment by carloshenrq** [comment]
Fala @Hyroshima,

Preciso de pouco mais de informações para dar uma olhada mais precisa...
Pelo que você disse, é sempre quando um personagem da classe Noviço (não aprendiz) é criado e quando um monstro qualquer ataca este personagem ou com qualquer outro personagem?

**Comment by Hyroshima** [comment]
@carloshenrq 

Opa manolo, com o update de hoje (11/06/2015) foram corrigidos os problemas, existiam 2 problema, esse de quando o noviço logava (esse aconteceu lá no hercules e foi corrigido) já o do mob usar habilidades pra atacar só aconteceu aqui no brA mais foi corrigido hoje, porem uma outra permanece mas é em relação ao banco de dados ou ou core mesmo, irei abrir um tópico...

http://forum.brathena.org/index.php/topic/22557-sql-truncated-for-column/

**Comment by carloshenrq** [comment]
Sem problema! Irei encerrar aqui então.

Forte abraço.
