### ISSUE TITLE
GdE 2.0 - Erro em NPC após tradução

### ISSUE THREAD

**Issue by lipespry** [brAthena/brAthena#100]
Após a tradução do nome dos NPCs, a quantidade de caracteres foi alterada. Logo, isso está causando este erro:
`[Depurar]: NPCEvent 'Dispositivo de Controle0-1#sc01::OnEnable' not found! (source: Dispositivo de Controle03#sc01)`

CORREÇÃO:

Arquivo:
`brAthena/npc/gde/2ed/2ed_principal.txt`

Buscar na linha ~1110:
```
// Dispositivos de Controle (3)
//============================================================
-	script	Dispositivo de Controle#template	-1,{
	.@GID = getcastledata(strnpcinfo(4),1);
	.@num = atoi(charat(strnpcinfo(1),15));
	.@var$ = "$agit_"+strnpcinfo(2);
	if (getcharid(2) == .@GID) {
		if (strcharinfo(0) == getguildmaster(.@GID)) {
```

Atualizar para:
`	.@num = atoi(charat(strnpcinfo(1),24)); `

Explicação:
`arug_cas01,247,52,0	duplicate(Dispositivo de Controle#template)	Dispositivo de Controle01#ar01	HIDDEN_NPC`
Nome do NPC: Dispositivo de Controle01#ar01
`charat(strnpcinfo(1),15)` recebe o caractere "C" que está na posição 15 (Começa a contar a partir do 0);
Com a atualização vai receber o caractere 24, que por sua vez é o número 1.

Esse erro ocorre por culpa da tradução que mudou o número de caracteres no nome do NPC duplicado, que no emulador "us-en" se chama "Control Device01#ar01". 

Att, LipESprY

**Comment by OrceBR** [comment]
Realmente. Irei fazer os testes e enviar a correção para o repositório assim que possível.

Por hora, obrigado pela colaboração @lipespry

**Comment by OrceBR** [comment]
AJustado.
