### ISSUE TITLE
Duvida, party atcommands

### ISSUE THREAD

**Issue by iMihael** [brAthena/brAthena#21]
Vocês já implementaram no emulador isso?

*getpartyname
*getpartymember 
*getpartyleader
*party_create
*party_destroy
*party_addmember
*party_delmember
*party_changeleader
*party_changeoption

Saiu a um tempo no rA / hercules e queria saber se tem no brA :3

**Comment by carloshenrq** [comment]
Algumas sim, mas a maioria ainda não...

getpartyname
https://github.com/brAthena/brAthena/blob/master/src/map/script.c#L7855

getpartymember
https://github.com/brAthena/brAthena/blob/master/src/map/script.c#L7881

getpartyleader
https://github.com/brAthena/brAthena/blob/master/src/map/script.c#L7918

As funções de party_* ainda não foram implementadas.

**Comment by Mihaelll** [comment]
Tendi, vlw carlos... no aguardo da implementação do resto <3 , estou pensando em criar um eventinho baseado nas partys dai por isso perguntei .-.

But, vlw novamente :+1:
