### ISSUE TITLE
Crash zeny +100.000

### ISSUE THREAD

**Issue by guihleao** [brAthena/brAthena#5]
Boa tarde pessoal, qualquer transação acima de 100.000 dá crash no servidor, compra, troca, venda. Incluindo algumas habilidades que usam esse valor de zeny (Como exemplo Explosão de Moedas).
 
Por gentileza, deem uma olhada ;)
 
Obrigado.

**Comment by Sh1raz** [comment]
Tentei reproduzir o problema diversas vezes, mas sem sucesso. Tem alguma configuração especial? A database do emulador (logs) está atualizada?

**Comment by guihleao** [comment]
Está atualizada, mas eu não uso logs de sql, apenas txt.

Percebi que tem algo relacionado com o log, pois na minha configuração se encontra:

// Faz log de alterações de zeny?
// Configurações dos filtros
// 0 - não faz log; 1 - faz log de qualquer mudança; 2.....1000000 - quantidade minima de zenys para logar.
log_zeny: 100000

Fiz testes e diminui o valor para 50000, o problema acontece com qualquer transação superior a 50000. O emulador talvez não esteja conseguindo criar o log de zeny em txt, por isso o erro.
