### ISSUE TITLE
Considerações a serem corrigidas

### ISSUE THREAD

**Issue by bagmf** [brAthena/brAthena#67]
1 - Formula da AD está incorreta, depois de pesquisar consegui duas formulas que chegam próximo ao original.
no código do battle.c pesquisa por: 
CASE CR_ACIDDEMONSTRATION 

em if_def renewal

substituir a antiga formula no if  md.damage e colocar:
md.damage = (int)((int64)7*tstatus->vit*sstatus->int_*sstatus->int_ / (10*(tstatus->vit+sstatus->int_)));

substituir no else na formula md.damage trocar o 70 por 120 

2 - CartCannon deve mudar o NK para 0x40, pois não está ignorando a flee do monstro.

**Comment by OrceBR** [comment]
Qual revisão do emulador você esta usando?
https://github.com/brAthena/brAthena/blob/master/src/map/battle.c#L4063

E qual é sua fonte?

**Comment by bagmf** [comment]
Quanto ao cálculo da AD foram testes que fiz manualmente no bRO.

Agora o CartCannon ignora a flee, iRO, kRO, euro, etc.

Minha revisão é  última postada aqui no GitHub, recompilei tudo do zero.
