### ISSUE TITLE
Warning ao compilar

### ISSUE THREAD

**Issue by HD-Scripts** [brAthena/brAthena#72]
https://github.com/brAthena/brAthena/blob/eb5736252eb3a0c28b3cbd151918f0ed6b73642d/src/map/pc.c#L4745

Erro: `pc.c: In function 'pc_dropitem':
pc.c:4745: warning: suggest parentheses around '&&' within '||'`

baixei ontem a versão do git

**Comment by OrceBR** [comment]
Corrigido no commit 1c99bb9
