### ISSUE TITLE
Erro nas skills do AB

### ISSUE THREAD

**Issue by QuodDG** [brAthena/brAthena#94]
As skills Offertorium e Magnificat deveriam cancelar uma a outra, mas não estão fazendo isso.
O erro se encontra no arquivo **status.c**.

Na linha 7526 deveria ficar assim:

> case SC_MAGNIFICAT:
> 	if (sc->data[SC_OFFERTORIUM]) 
> 		status_change_end(bl, SC_OFFERTORIUM, INVALID_TIMER);
> 	if(sc->option&OPTION_MADOGEAR) // Mado is immune to magnificat
> 		return 0;
> 	break;

Na linha 7758 deveria ficar assim:

> case SC_OFFERTORIUM:
>    if (sc->data[SC_MAGNIFICAT])
> 	status_change_end(bl, SC_MAGNIFICAT, INVALID_TIMER);
> break;

Além disso, percebi que a quantidade de SP consumido ao usar habilidades, estando com offertorium ativo, não muda. Mas essa parte ainda não achei onde consertar.

**Comment by OrceBR** [comment]
Estarei Verificando.

Por hora, obrigado pela coaboração @QuodDG

**Comment by OrceBR** [comment]
Ajustado.
