### ISSUE TITLE
Group_ID retornando automaticamente para 0

### ISSUE THREAD

**Issue by pagliahost** [brAthena/brAthena#97]
Caros,

De um tempo para cá, alguns NPCs que fazem o gerenciamento de VIP, adição de VIP, etc, eles estão setando no banco de dados o group_id para 1 porém ao logar na conta automaticamente o emulador está setando o group_id novamente para 0, saberiam me informar o que pode ser este problema?

@Protimus @carloshenrq @OrceBR @TioAkima  e demais companheiros!

**Comment by QuodDG** [comment]
Você está usando o sistema padrão do emulador e suas funções?

**Comment by pagliahost** [comment]
@QuodDG Na verdade um cliente está utilizando um NPC que sempre fornecemos há anos, que ele trocava no banco de dados o group_id, recentemente parece que o próprio emulador tem trocado automaticamente.

**Comment by QuodDG** [comment]
Atualize o nov para usar as seguintes funções:
add_time_vip(DIAS, HORAS, MINUTOS, SEGUNDOS);
show_time_vip();
A segunda mostra a quantidade de dias vip restantes em um dispbottom.

**Comment by OrceBR** [comment]
@pagliahost teria como me enviar o NPC para poder efetuar os testes?

**Comment by pagliahost** [comment]
@OrceBR Desculpe-nos pela demora em responder esse chamado, o mesmo foi resolvido retornando o sistema VIP original dentro de brathena.h.
